### ISSUE TITLE
Cannot access Azure Blob Store via Spark nor Drill

### ISSUE THREAD

**Issue by yorek** [Azure/DataScienceVM#14]
Hi, I'm trying to access an Azure Blob Store file via Spark or Drill. In both cases I have the following error (here shown in Spark):

```
sc.textFile("wasb://asa@dmstore1.blob.core.windows.net/TestQuery/InputMonitor/0_331b3d2e8ecd428398283b5d40d0e443_1.json").count()
java.io.IOException: No FileSystem for scheme: wasb
  at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2660)
  at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
  at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
  at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
  at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
  at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
  at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
  at org.apache.hadoop.mapred.FileInputFormat.singleThreadedListStatus(FileInputFormat.java:258)
  at org.apache.hadoop.mapred.FileInputFormat.listStatus(FileInputFormat.java:229)
  at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.java:315)
  at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:200)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:253)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:251)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.rdd.RDD.partitions(RDD.scala:251)
  at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:253)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:251)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.rdd.RDD.partitions(RDD.scala:251)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2092)
  at org.apache.spark.rdd.RDD.count(RDD.scala:1162)
  ... 49 elided

```

I've checked the configuration and in both cases the azure-storage and hadoop-azure jars are loaded.

In both cases I've configured my site_config.xml to be something like:

```
<?xml version="1.0" encoding="UTF-8" ?>
<configuration>
  <property>
    <name>fs.AbstractFileSystem.wasb.Impl</name>
    <value>org.apache.hadoop.fs.azure.Wasb</value>
  </property>
  <property>
    <name>fs.azure.account.key.dmstore1.blob.core.windows.net</name>
    <value>{my key here}</value>
  </property>
</configuration>
```

Any idea on how to solve the problem? Thanks!

**Comment by paulshealy1** [comment]
Hi, thanks for reaching out. Is this on the Ubuntu or Windows 2016 DSVM?

**Comment by yorek** [comment]
Windows 2016 DSVM. I did some research in the weekend and I've been able to have it running. You really have to carefully pick the correct jar versions. The version I've found working are the following:

- http://central.maven.org/maven2/org/apache/hadoop/hadoop-azure/2.7.7/hadoop-azure-2.7.7.jar
- http://central.maven.org/maven2/com/microsoft/azure/azure-storage/8.0.0/azure-storage-8.0.0.jar

download and put them in "jars" folder. You can then configure th4e core-site to store storage key:

```
<configuration>
  <property>
    <name>fs.azure.account.key.[STORAGE_ACCOUNT].blob.core.windows.net</name>
    <value>[KEY]</value>
  </property>
</configuration>

```
and then you can finally configure the storage plugin and use it
